### ISSUE TITLE
Inconsistency with transformation removal

### ISSUE THREAD

**Issue by Feliphysics** [LordAshes/TaleSpire-FileAccessPlugin#3]
Removing a transformation on kiki simply removes kiki's mesh, while removing a transformation on one of my custom minis (which don't use the AssetBundle format, but the obj/mtl format) does nothing. Both these problems get corrected with a board reload, after which the transformation will have been correctly removed. For all I know this could be intended behaviour, it should also be easy to reproduce, if it's needed I will upload a log file. This happens with both new and old transformations.

**Comment by LordAshes** [comment]
No. If the mesh is not removed on a Remove then this is a bug. I have
tested the removal of a OBJ/MTL transformation and it does work. Can you
please provide your player.log for the situation so that I can see if there
is anything in the log that may suggest why the problem occurred. Since a
board reload fixes the issue, the StatBlock is obviously updated but it
looks like the actual visual removal may have run into problems.

Lord Ashes



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Feliphysics** [comment]
In the following load I:
1. started the modded game (I left active only CMP and dependencies);
2. opened up a campaign that had my test board as default board (having 2 preapplied kikis and 4 preapplied custom transformations);
3. removed half of the transformations;
4. reloaded;
5. removed the other half;
6. reloaded;
7. transformed a mini into kiki and removed the transformation.

Everything behaved as described in the issue's text.

[Player.log](https://github.com/LordAshes/TaleSpire-FileAccessPlugin/files/6836599/Player.log)

If there is any problem with the log and you need another one let me know.

**Comment by LordAshes** [comment]
Looks like you are using CMP 5.0.1 but you didn't turn the diagnostic mode
on so no additional entries were placed in the log. Please go to r2ModMan.
Go to the Config Editor section (link on the left side). Find CMP. Edit the
Config and turn diagnostics to true. Don't forget to save.

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Feliphysics** [comment]
I 100% set the diagnostic mode to true, but I will indeed do it again and reupload in a few minutes.

**Comment by LordAshes** [comment]
This is probably a CMP issue not a FileAccessPlugin issue.

Lord Ashes

**Comment by Feliphysics** [comment]
I will then close this issue and reopen in in the appropriate page with the new log, sorry for the misplacement
